services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_HOST=db
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    volumes:
      - ./:/app
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  email:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  postgres_data:
  redis_data: